### ISSUE TITLE
unimorph_inflect.py is empty 

### ISSUE THREAD

**Issue by CarmenSaldana** [antonisa/unimorph_inflect#2]

**Comment by antonisa** [comment]
You don't need this file -- did you try installing from source as per the instructions?

**Comment by CarmenSaldana** [comment]
Thanks for the prompt response. I did install it from source, yes. What is the content of the unimorph_inflect import in py then?

**Comment by antonisa** [comment]
unimorph_inflect is the name of the package, and that's what is being imported -- it doesn't load anything from the unimorph_inflect.py file. Are you having any issues? If yes, it might be because you entered the python interpreter from the same directory as the one where you ran the installation?

Now, I honestly don't remember if the empty file is needed (as part of the installation) or if it's jut leftover from an older commit. :/

**Comment by CarmenSaldana** [comment]
Perfect, the file itself was the problem then, I eliminated the file and everything ran smoothly. Thanks!
